export * from './Bricks.page'
export * from './FAQ.page'
export * from './Home.page'
export * from './Minifigs.page'
export * from './OtherProducts.page'
export * from './PageNotFound.page'
export * from './Plates.page'
export * from './ReturnPolicy.page'
export * from './PrivacyPolicy.page'
export * from './Shipping.page'
export * from './Sitemap.page'
export * from './TermsAndConditions.page'
export * from './Tracking.page'

export * from './Login.page'
