export * from './Cart.page'
export * from './FAQ.page'
export * from './Home.page'
export * from './PageNotFound.page'
export * from './PrivacyPolicy.page'
export * from './Product.page'
export * from './Products.page'
export * from './ReturnPolicy.page'
export * from './Shipping.page'
export * from './Sitemap.page'
export * from './TermsAndConditions.page'
export * from './Tracking.page'

export * from './Login.page'
